name: Test TS Builds

on:
  push:
    branches: [main]

jobs:
  test-ts-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test TypeScript build
        run: |
          npm intall
          npm run build